name: flutter_uploader_example
version: 3.0.0-beta.3
description: Demonstrates how to use the flutter_uploader plugin.
publish_to: "none"

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  equatable: ^2.0.5
  file_picker: ^8.1.2
  flutter:
    sdk: flutter
  flutter_local_notifications: ^17.2.2
  flutter_uploader:
    path: ../
  image_picker: ^1.1.2
  path_provider: ^2.1.4
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
