name: flutter_uploader
description: A plugin for creating and managing upload tasks with optional
  background exection support.
version: 3.0.0
homepage: https://github.com/fluttercommunity/flutter_uploader
maintainer: Sebastian Roth (@ened)

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.4.11
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4

flutter:
  plugin:
    platforms:
      android:
        package: com.bluechilli.flutteruploader
        pluginClass: FlutterUploaderPlugin
      ios:
        pluginClass: FlutterUploaderPlugin

false_secrets:
  - example/ios/Runner/GoogleService-Info.plist
